# Generated by Django 6.0.7 on 2026-08-04 00:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('naver', 'Naver'), ('tavily', 'Tavily')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('content', models.TextField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('length_option', models.CharField(blank=True, max_length=50)),
                ('tone_option', models.CharField(blank=True, max_length=50)),
                ('purpose_text', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='reports.document')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reports.searchquery'),
        ),
        migrations.CreateModel(
            name='ReportChunkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_usages', to='reports.documentchunk')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_usages', to='reports.report')),
            ],
            options={
                'unique_together': {('report', 'document_chunk')},
            },
        ),
    ]
